-- MEMBER 테이블 생성
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	USERID		VARCHAR2(20),
	USERPW		VARCHAR2(20)	NOT NULL,
	USERNAME	VARCHAR2(20)	NOT NULL,
	MOBILE		VARCHAR2(13)	NOT NULL,
	MOBILE_ID	VARCHAR2(128)	UNIQUE,
	EMAIL		VARCHAR2(30)	NOT NULL,
	BIRTH		VARCHAR2(6)		NOT NULL,
	GRADE		VARCHAR2(1)		DEFAULT 'G',
	USE_COUNT	NUMBER(3)		DEFAULT 0
);

ALTER TABLE MEMBER
ADD CONSTRAINT PK_MEMBER_USERID PRIMARY KEY(USERID);

-- ROOM_TYPE 테이블 생성

DROP TABLE ROOM_TYPE CASCADE CONSTRAINTS;
DROP SEQUENCE ROOM_TYPE_SEQ;

CREATE TABLE ROOM_TYPE (
	ROOM_TYPE_NO	NUMBER(2),
	TYPE_NAME		VARCHAR2(20)	NOT NULL,
	BED				VARCHAR2(20)	NOT NULL,
	LIMIT_NUM		NUMBER(2)
);

CREATE SEQUENCE ROOM_TYPE_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE ROOM_TYPE
ADD CONSTRAINT PK_ROOM_TYPE_NO PRIMARY KEY(ROOM_TYPE_NO);

-- ROOM 테이블 생성
DROP TABLE ROOM;
DROP TABLE SEQUENCE ROOM_SEQ;

CREATE TABLE ROOM (
	ROOM_NO			NUMBER(10),
	FLOOR			VARCHAR2(2)		NOT NULL,
	AVAILABILITY	VARCHAR2(1)		DEFAULT 'O',
	PRICE			VARCHAR2(7)		NOT NULL,
	ROOM_TYPE_NO	NUMBER(2)		NOT NULL
);

CREATE SEQUENCE ROOM_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE ROOM
ADD CONSTRAINT PK_ROOM_ROOM_NO PRIMARY KEY(ROOM_NO);

ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_ROOM_TYPE_NO FOREIGN KEY(ROOM_TYPE_NO)
REFERENCES ROOM_TYPE(ROOM_TYPE_NO);

-- ROOM_PICS 테이블 생성
DROP TABLE ROOM_PICS CASCADE CONSTRAINTS;
DROP SEQUENCE ROOM_PICS_SEQ;

CREATE TABLE ROOM_PICS (
	PICS_NO			NUMBER(10),
	PICS_PATH		VARCHAR2(50)	NOT NULL,
	ROOM_TYPE_NO	NUMBER(2)		NOT NULL,
	BEACON_MINOR	NUMBER(15)
);

CREATE SEQUENCE ROOM_PICS_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE ROOM_PICS
ADD CONSTRAINT PK_ROOM_PICS_PICS_NO PRIMARY KEY(PICS_NO);

ALTER TABLE ROOM_PICS
ADD CONSTRAINT FK_ROOM_PICS_ROOM_TYPE_NO FOREIGN KEY(ROOM_TYPE_NO)
REFERENCES ROOM_TYPE(ROOM_TYPE_NO);
 
-- FACILITY 테이블 생성
DROP TABLE FACILITY;
DROP SEQUENCE FACILITY_SEQ;

CREATE TABLE FACILITY (
	FAC_NO			NUMBER(10),
	FAC_NAME		VARCHAR2(20)	NOT NULL,
	FAC_INFO		VARCHAR2(50)	NOT NULL,
	AVAILABILITY	VARCHAR2(1)		DEFAULT 'O',
	BEACON_MINOR	NUMBER(15)
);

CREATE SEQUENCE FACILITY_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE FACILITY
ADD CONSTRAINT PK_FACILITY_FAC_NO PRIMARY KEY(FAC_NO);

-- FAC_PICS 테이블 생성
DROP TABLE FAC_PICS CASCADE CONSTRAINTS;
DROP SEQEUNCE FAC_PICS_SEQ;

CREATE TABLE FAC_PICS (
	PICS_NO		NUMBER(10),
	PICS_PATH	VARCHAR2(50)	NOT NULL,
	FAC_NO		NUMBER(10)		NOT NULL
);

CREATE SEQUENCE FAC_PICS_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE FAC_PICS
ADD CONSTRAINT PK_FAC_PICS_PICS_NO PRIMARY KEY(PICS_NO);

ALTER TABLE FAC_PICS
ADD CONSTRAINT FK_FAC_PICS_FAC_NO FOREIGN KEY(FAC_NO)
REFERENCES FACILITY(FAC_NO);

-- RESERVATION 테이블 생성
DROP TABLE RESERVATION;
DROP TABLE RESERVATION_SEQ;

CREATE TABLE RESERVATION (
	RESERVATION_NO		NUMBER(15),
	USERID				VARCHAR2(20)	NOT NULL,
	ROOM_TYPE_NO		NUMBER(2)		NOT NULL,
	HEAD_COUNT			NUMBER(2)		NOT NULL,
	CHKIN_DATE			VARCHAR2(10)	NOT NULL,
	CHKOUT_DATE			VARCHAR2(10)	NOT NULL,
	MEMO				VARCHAR2(50)
);

CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE RESERVATION
ADD CONSTRAINT PK_RESERVATION_RESERVATION_NO PRIMARY KEY(RESERVATION_NO);

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RESERVATION_USERID FOREIGN KEY(USERID)
REFERENCES MEMBER(USERID);

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RESERVATION_ROOM_TYPE_NO FOREIGN KEY(ROOM_TYPE_NO)
REFERENCES ROOM_TYPE(ROOM_TYPE_NO);

--EVENT 테이블 생성
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE EVENT_SEQ;;

CREATE TABLE EVENT (
	EVENT_NO		NUMBER(10),
	EVENT_TYPE		VARCHAR2(10)	NOT NULL,
	WINNER_LIMIT	NUMBER(2)		NOT NULL,
	BEACON_MINOR	NUMBER(15)
);

CREATE SEQUENCE EVENT_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE EVENT
ADD CONSTRAINT PK_EVENT_EVENT_NO PRIMARY KEY (EVENT_NO);

-- EVENT_WINNER 테이블 생성
DROP TABLE EVENT_WINNER;

CREATE TABLE EVENT_WINNER (
	WINNER		VARCHAR2(20),
	EVENT_NO	NUMBER(10)		NOT NULL
);

ALTER TABLE EVENT_WINNER
ADD CONSTRAINT PK_EVENT_WINNER_WINNER PRIMARY KEY(WINNER);

ALTER TABLE EVENT_WINNER
ADD CONSTRAINT FK_EVENT_WINNER_EVENT_NO FOREIGN KEY(EVENT_NO)
REFERENCES EVENT(EVENT_NO);

COMMIT;
