
DROP TABLE EVENT_PART;
DROP TABLE TIME_EVENT
DROP TABLE EVENT_WINNER;
DROP TABLE TIME_EVENT;
DROP TABLE ROOM_PICS;
DROP TABLE FAC_PICS;
DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE ROOM_TYPE;
DROP TABLE FACILITY;
DROP TABLE MEMBER;

DROP SEQUENCE ROOM_SEQ;
DROP SEQUENCE ROOM_PICS_SEQ;
DROP SEQUENCE FACILITY_SEQ;
DROP SEQUENCE FAC_PICS_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE EVENT_SEQ;
DROP SEQUENCE ROOM_TYPE_SEQ;
DROP SEQUENCE EVENT_PART_SEQ;

-- MEMBER 테이블 생성
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	USERID		VARCHAR2(20),
	USERPW		VARCHAR2(20)	NOT NULL,
	USERNAME	VARCHAR2(20)	NOT NULL,
	MOBILE		VARCHAR2(13)	NOT NULL,
	MOBILE_ID	VARCHAR2(300)	UNIQUE,
	EMAIL		VARCHAR2(30)	NOT NULL,
	BIRTH		VARCHAR2(6)		NOT NULL,
	GRADE		VARCHAR2(2)		DEFAULT 'G',
	USE_COUNT	NUMBER(3)		DEFAULT 0
);

ALTER TABLE MEMBER
ADD CONSTRAINT PK_MEMBER_USERID PRIMARY KEY(USERID);

-- ROOM_TYPE 테이블 생성

DROP TABLE ROOM_TYPE CASCADE CONSTRAINTS;
DROP SEQUENCE ROOM_TYPE_SEQ;

CREATE TABLE ROOM_TYPE (
	ROOM_TYPE_NO	NUMBER(3),
	TYPE_NAME		VARCHAR2(20)	NOT NULL,
	BED				VARCHAR2(20)	NOT NULL,
	PRICE			VARCHAR2(10)	NOT NULL,
	LIMIT_NUM		NUMBER(2)
);

ALTER TABLE ROOM_TYPE
ADD CONSTRAINT PK_ROOM_TYPE_NO PRIMARY KEY(ROOM_TYPE_NO);

-- ROOM 테이블 생성
DROP TABLE ROOM;
DROP SEQUENCE ROOM_SEQ;

CREATE TABLE ROOM (
	ROOM_NO			NUMBER(10),
	FLOOR			VARCHAR2(2)		NOT NULL,
	AVAILABILITY	VARCHAR2(1)		DEFAULT 'O',
	ROOM_TYPE_NO	NUMBER(3)		NOT NULL,
	BEACON_MINOR	NUMBER(15)
);

CREATE SEQUENCE ROOM_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE ROOM
ADD CONSTRAINT PK_ROOM_ROOM_NO PRIMARY KEY(ROOM_NO);

ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_ROOM_TYPE_NO FOREIGN KEY(ROOM_TYPE_NO)
REFERENCES ROOM_TYPE(ROOM_TYPE_NO);

-- ROOM_PICS 테이블 생성
DROP TABLE ROOM_PICS CASCADE CONSTRAINTS;
DROP SEQUENCE ROOM_PICS_SEQ;

CREATE TABLE ROOM_PICS (
	PICS_NO			NUMBER(10),
	PICS_PATH		VARCHAR2(200),
	ROOM_TYPE_NO	NUMBER(3)		NOT NULL,
	ORGNAME			VARCHAR2(2000),
	NEWNAME			VARCHAR2(2000)
);

CREATE SEQUENCE ROOM_PICS_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE ROOM_PICS
ADD CONSTRAINT PK_ROOM_PICS_PICS_NO PRIMARY KEY(PICS_NO);

ALTER TABLE ROOM_PICS
ADD CONSTRAINT FK_ROOM_PICS_ROOM_TYPE_NO FOREIGN KEY(ROOM_TYPE_NO)
REFERENCES ROOM_TYPE(ROOM_TYPE_NO);
 
-- FACILITY 테이블 생성
DROP TABLE FACILITY;
DROP SEQUENCE FACILITY_SEQ;

CREATE TABLE FACILITY (
	FAC_NO			NUMBER(10),
	FAC_NAME		VARCHAR2(20)	NOT NULL,
	FAC_INFO		VARCHAR2(50)	NOT NULL,
	AVAILABILITY	VARCHAR2(1)		DEFAULT 'O',
	BEACON_MINOR	NUMBER(15)
);

CREATE SEQUENCE FACILITY_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE FACILITY
ADD CONSTRAINT PK_FACILITY_FAC_NO PRIMARY KEY(FAC_NO);

-- FAC_PICS 테이블 생성
DROP TABLE FAC_PICS CASCADE CONSTRAINTS;
DROP SEQEUNCE FAC_PICS_SEQ;

CREATE TABLE FAC_PICS (
	PICS_NO		NUMBER(10),
	PICS_PATH	VARCHAR2(200),
	FAC_NO		NUMBER(10)		NOT NULL,
	ORGNAME			VARCHAR2(2000),
	NEWNAME			VARCHAR2(2000)
);

CREATE SEQUENCE FAC_PICS_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE FAC_PICS
ADD CONSTRAINT PK_FAC_PICS_PICS_NO PRIMARY KEY(PICS_NO);

ALTER TABLE FAC_PICS
ADD CONSTRAINT FK_FAC_PICS_FAC_NO FOREIGN KEY(FAC_NO)
REFERENCES FACILITY(FAC_NO);

-- RESERVATION 테이블 생성
DROP TABLE RESERVATION;
DROP SEQUENCE RESERVATION_SEQ;

CREATE TABLE RESERVATION (
	RESERVATION_NO		VARCHAR2(15),
	USERID				VARCHAR2(20)	NOT NULL,
	ROOM_TYPE_NO		NUMBER(3)		NOT NULL,
	HEAD_COUNT			NUMBER(2)		NOT NULL,
	CHKIN_DATE			VARCHAR2(10)	NOT NULL,
	CHKOUT_DATE			VARCHAR2(10)	NOT NULL,
	MEMO				VARCHAR2(50),
	ROOM_NO				NUMBER(10)
);

CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE RESERVATION
ADD CONSTRAINT PK_RESERVATION_RESERVATION_NO PRIMARY KEY(RESERVATION_NO);

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RESERVATION_USERID FOREIGN KEY(USERID)
REFERENCES MEMBER(USERID);

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RESERVATION_ROOM_TYPE_NO FOREIGN KEY(ROOM_TYPE_NO)
REFERENCES ROOM_TYPE(ROOM_TYPE_NO);

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RESERVATION_ROOM_NO FOREIGN KEY(ROOM_NO)
REFERENCES ROOM(ROOM_NO);

--TIME_EVENT 테이블 생성
DROP TABLE TIME_EVENT CASCADE CONSTRAINTS;

CREATE TABLE TIME_EVENT (
	BEACON_MINOR	NUMBER(15),
	FAC_NAME		VARCHAR2(20) NOT NULL,
	EVENT_TIME		VARCHAR2(30),
	WINNER			VARCHAR2(30)
);

ALTER TABLE TIME_EVENT
ADD CONSTRAINT PK_TIME_EVENT PRIMARY KEY (BEACON_MINOR, EVENT_TIME);

COMMIT;
